name: Pruebas

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  cola-offline:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
      - name: Preparar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Comprobar sintaxis
        run: npm run check
      - name: Ejecutar pruebas
        run: npm test
